### ISSUE TITLE
Directory `eval` is missing

### ISSUE THREAD

**Issue by mkovaxx** [pschlump/lexie#1]
It's imported in `mt/mt.go` as `"github.com/pschlump/lexie/eval"`, but it doesn't exist.
https://github.com/pschlump/lexie/blob/d3f42d3896b6d5dffe47e88cd84f1cf7658a9108/mt/mt.go#L9

**Comment by pschlump** [comment]
I added the missing code in.  
The main program in ./cli now compiles.  
This is still a work-in-progress - Let me know how you are planning on using this and I can help.

**Comment by mkovaxx** [comment]
Hey Philip, thanks for the quick fix! :)

I'm new to Go, and I was looking for an equivalent to lex / flex (I often write lexers and parsers at work).
I was actually looking at this repository on Sourcegraph, but the missing directory was causing problems.
Thanks to your fix, it works now: https://sourcegraph.com/github.com/pschlump/lexie

**Comment by pschlump** [comment]
The intent for lexie was a replacement in Go for flex that allows for dynamic changes to lexical analysis.  I a plan on writing documentation and finishing the tests for it but I am swamped with other work for a few weeks.   Hopefully lexie will be useful to you.  If you have other problems don't hesitate to open a new issue.
